# Generated by Django 2.0.6 on 2018-06-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstance',
            new_name='ProductInstance',
        ),
    ]
